root = "."
tmp_dir = "tmp"

[build]
  bin = "./tmp/templTest"
  cmd = "npx tailwindcss --config configs/tailwind.config.js -i configs/input.css -o assets/css/styles.css && templ generate && go build -o ./tmp/templTest ."
  delay = 1000
  exclude_dir = ["assets", "tmp", "vendor"]
  exclude_file = []
  exclude_regex = [".*_templ.go"]
  exclude_unchanged = false
  follow_symlink = false
  full_bin = ""
  include_dir = []
  include_ext = ["go", "tpl", "tmpl", "templ", "html", "css"]
  kill_delay = "0s"
  log = "build-errors.log"
  send_interrupt = false
  stop_on_error = true

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  time = false

[misc]
  # Delete tmp directory on exit
  clean_on_exit = true

[screen]
  clear_on_rebuild = true
  keep_scroll = true